export const LABELS = {
  app: {
    name: 'WellMatch',
    tagline: 'Conectando pessoas por hábitos saudáveis',
  },
  common: {
    loading: 'Carregando...',
    error: 'Erro',
    success: 'Sucesso',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    retry: 'Tentar novamente',
    back: 'Voltar',
    save: 'Salvar',
    delete: 'Excluir',
    send: 'Enviar',
  },
  auth: {
    login: 'Entrar',
    register: 'Criar conta',
    email: 'Email',
    password: 'Senha',
    name: 'Nome',
    logout: 'Sair',
    noAccount: 'Não tem conta?',
    hasAccount: 'Já tem conta?',
  },
  onboarding: {
    title: 'Vamos começar',
    intro: 'Descubra pessoas com hábitos saudáveis perto de você',
    intent: 'Qual sua intenção principal?',
    goals: 'Quais seus objetivos de bem-estar?',
    activities: 'Quais atividades você prefere?',
    availability: 'Quando você está disponível?',
    intensity: 'Qual sua intensidade preferida?',
    privacy: 'Suas informações estão seguras',
    source: 'Como você quer fornecer seus dados?',
    completed: 'Onboarding concluído!',
    next: 'Próximo',
    continue: 'Continuar',
    finish: 'Concluir',
  },
  match: {
    screen: 'Match',
    likes: 'Curtidas',
    superLike: 'Super Like',
    noCandidates: 'Nenhum candidato disponível no momento',
    reportUser: 'Denunciar usuário',
    blockUser: 'Bloquear',
    unblockUser: 'Desbloquear',
  },
  messages: {
    screen: 'Mensagens',
    empty: 'Nenhuma conversa ainda',
    typeMessage: 'Digite sua mensagem...',
    send: 'Enviar',
  },
  profile: {
    screen: 'Perfil',
    edit: 'Editar perfil',
    privacy: 'Privacidade',
    smartwatch: 'Conectar Smartwatch',
    healthDashboard: 'Painel de Saúde',
    exportData: 'Exportar dados',
    deleteAccount: 'Excluir conta',
    adminPanel: 'Painel Admin',
  },
  challenges: {
    screen: 'Desafios',
    active: 'Ativos',
    completed: 'Concluídos',
    noActive: 'Nenhum desafio ativo',
    noCompleted: 'Nenhum desafio concluído',
    create: 'Criar desafio',
    progress: 'Progresso',
  },
  health: {
    dashboard: 'Painel de Saúde',
    steps: 'Passos',
    sleep: 'Sono',
    heartRate: 'Frequência cardíaca',
    calories: 'Calorias',
    sync: 'Sincronizar',
    lastSync: 'Última sincronização',
    noData: 'Nenhum dado disponível',
  },
  privacy: {
    screen: 'Privacidade',
    consentTitle: 'Permissões de dados',
    consentDescription: 'Gerencie quais métricas de saúde você compartilha',
    grant: 'Permitir',
    revoke: 'Revogar',
    exportTitle: 'Exportar dados',
    exportDescription: 'Baixe todos os seus dados pessoais',
    deleteTitle: 'Excluir conta',
    deleteDescription: 'Remova permanentemente sua conta e dados',
    confirmDelete: 'Tem certeza que deseja excluir sua conta?',
  },
  errors: {
    network: 'Erro de conexão. Verifique sua internet',
    default: 'Algo deu errado. Tente novamente',
  },
};
